spring:
  application:
    name: Quizzzin
  datasource:
    url: jdbc:postgresql://localhost:5432/Quizzzin
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:sql/necessary_data.sql, classpath:sql/dummy/puzzles.sql
server:
  servlet:
    context-path: /quizzzin