spring:
  application:
    name: Quizzzin
  datasource:
    url: jdbc:postgresql://localhost:5432/Quizzzin
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
      data-locations: classpath:static/sql/necessary_data.sql, classpath:static/sql/dummy/*.sql
server:
  servlet:
    context-path: /quizzzin